apiVersion: v2
name: postgres
description: PostgreSQL deployed via bjw-s app-template
type: application
version: 0.1.0
appVersion: "18.2"

dependencies:
  - name: app-template
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts
